config/routes.rb
Rails.application.routes.draw do

  root to: 'banner_people#index'
  resources :banner_people, only: [:index, :show, :update]
  resources :advisements, only: :update
end

app/models/advisement.rb
class Advisement < ApplicationRecord
  belongs_to :banner_person
  belongs_to :house
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/banner_person.rb
class BannerPerson < ApplicationRecord
  belongs_to :house
  has_many :handouts, dependent: :destroy
  has_many :loyalty_points, dependent: :destroy
  has_many :advisements, dependent: :destroy
  validates_presence_of :name
end

app/models/handout.rb
class Handout < ApplicationRecord
  belongs_to :banner_person
  belongs_to :house
  validates_presence_of :date, :value
  validates :value, numericality: { greater_than_or_equal_to: 200,  less_than_or_equal_to: 20_000 }
  validate :value_must_be_divisible_by_100

  def value_must_be_divisible_by_100
    if value.present? && value % 100 != 0
      errors.add(:value, "must be divisible by 100")
    end
  end
end

app/models/house.rb
class House < ApplicationRecord
  has_many :banner_people, dependent: :destroy
  has_many :handouts, dependent: :destroy
  has_many :advisements, dependent: :destroy
  validates_presence_of :name
end

app/models/loyalty_point.rb
class LoyaltyPoint < ApplicationRecord
  belongs_to :banner_person
  validates_presence_of :date, :value
  validates :value, numericality: { greater_than_or_equal_to: 5.0,  less_than_or_equal_to: 18.0 }
end

app/controllers/advisements_controller.rb
class AdvisementsController < ApplicationController

  def update
    @advisement = Advisement.find(params[:id])

    respond_to do |format|
      if @advisement.update(advisement_params)
        format.html { redirect_to @advisement.banner_person, notice: 'advisement was successfully updated.' }
        format.json { render :show, status: :ok, location: @advisement }
      else
        format.html { redirect_to @advisement.banner_person, error: 'advisement not successfully updated' }
        format.json { render json: @advisement.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def advisement_params
      params.require(:advisement).permit(:date, :value)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/banner_people_controller.rb
class BannerPeopleController < ApplicationController
  include BannerPersonStatistics

  def index
    @banner_people = BannerPerson.all
  end

  def show
    @banner_person = BannerPerson.find(params[:id])
    @handouts = @banner_person.handouts
    @loyalty_points = @banner_person.loyalty_points
    @graph_data = graph_data( @banner_person)
    @table_data = table_data(@banner_person.advisements, @graph_data)

    gon.dates = @graph_data.map { |datum| datum[:date].strftime("%b %d") }
    gon.handouts = @graph_data.map { |datum|
      datum[:handout] ? datum[:handout].value : nil
    }
    gon.loyalty_points = @graph_data.map.with_index { |datum, index|
      datum[:loyalty_point] ? [index, datum[:loyalty_point].value] : nil
    }.compact
  end

end

app/controllers/concerns/banner_person_statistics.rb
module BannerPersonStatistics
  extend ActiveSupport::Concern

  def graph_data(banner_person)
    graph_data = []
    house = banner_person.handouts.first.house

    (1..31).each do |day|
      date = Date.new(2019, 1, day)


      handout = banner_person.handouts.find { |handout| handout.date == date }
      loyalty_point = banner_person.loyalty_points.find do |loyalty_point|
        loyalty_point.date == date
      end

      house = handout.house if handout

      if handout || loyalty_point
        graph_data.push({
          date: date,
          handout: handout,
          loyalty_point: loyalty_point,
          house: house
        })
      else
        graph_data.push({
          date: date
        })
      end
    end

    graph_data
  end

  def table_data(advisements, graph_data)
    table_data = graph_data.select { |datum| datum[:handout] || datum[:loyalty_point] }.deep_dup
    previous_advisement = nil

    advisements.each do |advisement|
      datum = table_data.find { |datum| datum[:date] == advisement.date }

      if datum
        datum[:advisement] = advisement
      else
        table_data.push({
          date: advisement.date,
          advisement: advisement,
          house: advisement.house,
        })
      end

      if previous_advisement
        find_percent_accepted(table_data, previous_advisement, advisement.date)
      end

      previous_advisement = advisement
    end

    table_data.sort! { |a, b| a[:date] <=> b[:date] }
    end_date = table_data.last[:date] + 1.day
    find_percent_accepted(table_data, previous_advisement, end_date)

    table_data
  end

  def find_percent_accepted(table_data, advisement, end_date)
    data_between_advisements = table_data.select { |datum|
      datum[:date] >= advisement.date && datum[:date] < end_date
    }

    handouts = data_between_advisements.map { |datum| datum[:handout] }.compact

    # calculate acceptance percentage
    percentage = calculate_percentage(handouts, advisement)

    data_between_advisements.each { |datum_between_advisements|
      datum_between_advisements[:percent_accepted] = percentage
    }
  end

  def calculate_percentage(handouts, previous_advisement)
    matching = handouts.count { |handout| handout.value == previous_advisement.value }
    decimal = matching / handouts.count.to_f
    (decimal * 100).round(1)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/banner_people/_advisement_modal.slim
button.btn.btn-primary.btn-sm.edit-button type="button" data-toggle="modal" data-target="##{modal_id}" Edit Advisement

.modal.fade id=modal_id tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true"
  .modal-dialog.modal-dialog-centered role="document"
    .modal-content
      .modal-header
        h5.modal-title#exampleModalCenterTitle Edit Advisement
        button type="button" class="close" data-dismiss="modal" aria-label="Close"
          span aria-hidden="true" &times;
      .modal-body
        = simple_form_for [advisement], method: "patch" do |f|
          = f.input :value
          = f.input :date
          = f.submit "Update", class: "btn btn-primary"

app/views/banner_people/_graph.html.slim
.graph-container

  #container style="min-width: 310px; height: 400px; margin: 0 auto"

javascript:
  Highcharts.chart('container', {
    chart: {
      zoomType: 'xy'
    },
    title: {
      text: 'Handouts and Loyalty Points Monthly Report'
    },
    xAxis: [{
      categories: gon.dates,
      crosshair: true
    }],
    yAxis: [{ // Primary yAxis
      labels: {
        format: '{value}',
        style: {
          color: Highcharts.getOptions().colors[0]
        }
      },
      title: {
        text: 'Handouts',
        style: {
          color: Highcharts.getOptions().colors[0]
        }
      }
    }, { // Secondary yAxis
      title: {
        text: 'Loyalty Points',
        style: {
          color: Highcharts.getOptions().colors[1]
        }
      },
      labels: {
        format: '{value}',
        style: {
          color: Highcharts.getOptions().colors[1]
        }
      },
      opposite: true
    }],
    tooltip: {
      shared: true
    },
    legend: {
      layout: 'vertical',
      align: 'left',
      x: 120,
      verticalAlign: 'top',
      y: 100,
      floating: true,
      backgroundColor: (Highcharts.theme && Highcharts.theme.legendBackgroundColor) || 'rgba(255,255,255,0.25)'
    },
    series: [{
      name: 'Handouts',
      type: 'column',
      data: gon.handouts,
    }, {
      name: 'Loyalty Points',
      type: 'spline',
      yAxis: 1,
      data: gon.loyalty_points,
    }]
  });

app/views/banner_people/_table.html.slim
h3.table_heading Progress Table

.extend_view
  | <input type="radio" id="simple" name="tab" checked=true />
    <label for="simple">Simple Table View</label>
    <input type="radio" id="extended" name="tab" />
    <label for="extended">Enhanced View</label>

.banner_person_extended_table id ="extended_table" style="display:none;"
  table class = "banner_person_table"
    thead
      tr
        th Date
        th House ID
        th House
        th.td_number Handout
        th.td_number Loyalty Points
        th.td_number Advisement
        th.td_number % Accepted

    tbody
      - @table_data.each do |datum|
        - house = datum[:house]
        tr border="1"
          td
            p = datum[:date].strftime("%b %d, %Y")
          td
            p = "#{datum[:house]&.prefix}#{@banner_person.id} "
          td
            p = datum[:house]&.name
          td.td_number
            p = datum[:handout] ? number_with_delimiter(datum[:handout].value) : "—"
          td.td_number
            p = datum[:loyalty_point] ? datum[:loyalty_point].value : "—"

          - advisement = datum[:advisement]
          - if advisement
            td.td_number
              p = number_with_delimiter(advisement.value)
            td.td_number
              p = datum[:percent_accepted] ? "#{datum[:percent_accepted]}%" : "—"
            td = render 'advisement_modal', advisement: advisement, modal_id: "extended_modal_#{advisement.id}"
          - else
            td.td_number

            td.td_number
              p = datum[:percent_accepted] ? "#{datum[:percent_accepted]}%" : "—"


.banner_person_simple_table id ="simple_table"
  table class = "banner_person_table"
    thead
      tr
        th Date
        th.td_number Handout
        th.td_number Loyalty Points
        th.td_number Advisement

    tbody
      - @table_data.each do |datum|
        - house = datum[:house]
        tr border="1"
          td
            p = datum[:date].strftime("%b %d, %Y")


          td.td_number
            p = datum[:handout] ? number_with_delimiter(datum[:handout].value) : "—"
          td.td_number
            p = datum[:loyalty_point] ? datum[:loyalty_point].value : "—"

          - advisement = datum[:advisement]
          - if advisement
            td.td_number
              p = number_with_delimiter(advisement.value)
            td = render 'advisement_modal', advisement: advisement, modal_id: "simple_modal_#{advisement.id}"
          - else
            td.td_number

app/views/banner_people/index.html.slim
.snow class="layer1 a"
.snow class="layer1"
.snow class="layer2 a"
.snow class="layer2"
.snow class="layer3 a"
.snow class="layer3"
.banner-people-container
  h1 Banner People Standings
  table class = "banner_people_table"
    thead
      tr.bottom-border
        th
          h4 Banner Person
        th
          h4 House
        th
          h4 Loyalty Points
        th
          h4

      - @banner_people.each do |person|
        tr
          td
            p = person.name
          td
            p = person.house.name
          td
            p = person.loyalty_points.last.value
          td.btn = link_to "VIEW", banner_person_path(person)

app/views/banner_people/show.html.slim
= link_to "← back", banner_people_path, class: "btn btn-primary back_button"
.banner_person_container
  h1 = @banner_person.name
  h3 = "House #{ @banner_person.house.name }"

  = render "graph"

  = render "table"

app/views/layouts/application.html.erb
<%= include_gon %>

<!DOCTYPE html>
<html>
  <head>
    <title>BannerPersonSkeleton</title>
    <%= Gon::Base.render_data %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link href="https://fonts.googleapis.com/css?family=Cinzel|Cormorant+Garamond&display=swap" rel="stylesheet">
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>